version: '3'
services:
    #reverseproxy:
    #    image: a3ex1984/reverseproxy
    #    ports:
    #        - 8080:8080
    #    restart: always
    #    depends_on:
    #      - backend-user
    #      - backend-feed
            
    backend-user:
        image: a3ex1984/microservicesuser
        volumes:
            - $HOME/.aws:/root/.aws
        environment:
            POSTGRES_USERNAME: $POSTGRES_USERNAME
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
            POSTGRES_DB: $POSTGRES_DB
            POSTGRES_HOST: $POSTGRES_HOST
            AWS_REGION: $AWS_REGION
            AWS_PROFILE: $AWS_PROFILE
            AWS_BUCKET: $AWS_BUCKET
            URL: "http://localhost:8100"
            JWT_SECRET: $JWT_SECRET

    backend-feed:
        image: a3ex1984/microservicesfeed
        volumes:
            - $HOME/.aws:/root/.aws
        environment: 
            POSTGRES_USERNAME: $POSTGRES_USERNAME
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
            POSTGRES_DB: $POSTGRES_DB
            POSTGRES_HOST: $POSTGRES_HOST
            AWS_REGION: $AWS_REGION
            AWS_PROFILE: $AWS_PROFILE
            AWS_BUCKET: $AWS_BUCKET
            URL: "http://localhost:8100"
            JWT_SECRET: $JWT_SECRET


    frontend:
        image: a3ex1984/microservicesfeed
        ports: 
            - "8100:80"

        

 

  